/**
 * Workflow Template Schema
 *
 * Defines the structure for visual workflow templates that can be:
 * 1. Loaded into the workflow canvas
 * 2. Converted to code scaffolds
 * 3. Generated by AI agents from prompts
 */

// Node types available in the workflow system
export type WorkflowNodeType =
  | 'trigger'      // Entry points (events, schedules, webhooks)
  | 'action'       // Operations (create, update, delete)
  | 'condition'    // Decision points (if/else)
  | 'database'     // Data operations (CRUD, migrations)
  | 'api'          // HTTP endpoints
  | 'ui'           // User interface components
  | 'agent'        // AI agent execution
  | 'notification'; // Alerts and messages

// Template categories
export type TemplateCategory =
  | 'saas'
  | 'web'
  | 'mobile'
  | 'wordpress'
  | 'mcp'
  | 'devops'
  | 'ai';

// Complexity levels
export type TemplateComplexity = 'simple' | 'medium' | 'complex';

// Platform/stack types
export type TemplatePlatform =
  | 'react'
  | 'node'
  | 'wordpress'
  | 'expo'
  | 'docker'
  | 'gcp'
  | 'universal';

// Scaffold types for code generation
export type ScaffoldType =
  | 'monorepo'
  | 'single-app'
  | 'plugin'
  | 'theme'
  | 'service';

// Position for visual layout
export interface Position {
  x: number;
  y: number;
}

// Node configuration based on type
export interface NodeConfig {
  agentName?: string;        // For agent nodes
  endpoint?: string;         // For API nodes
  component?: string;        // For UI nodes
  tableName?: string;        // For database nodes
  event?: string;            // For trigger nodes
  channel?: string;          // For notification nodes
  condition?: string;        // For condition nodes
  command?: string;          // For action nodes
  [key: string]: unknown;    // Additional config
}

// Node data structure
export interface WorkflowNodeData {
  label: string;
  nodeType: WorkflowNodeType;
  description?: string;
  config?: NodeConfig;
}

// Workflow node (ReactFlow compatible)
export interface WorkflowNode {
  id: string;
  type: 'workflow';
  position: Position;
  data: WorkflowNodeData;
}

// Workflow edge (ReactFlow compatible)
export interface WorkflowEdge {
  id: string;
  source: string;
  target: string;
  label?: string;
  animated?: boolean;
  type?: string;
}

// Stack profile for code generation
export interface StackProfile {
  frontend?: {
    framework: 'react' | 'nextjs' | 'vue' | 'expo' | 'wordpress';
    styling: 'tailwind' | 'css-modules' | 'styled-components' | 'sass';
    state?: 'zustand' | 'redux' | 'context' | 'jotai';
  };
  backend?: {
    runtime: 'node' | 'bun' | 'deno' | 'php';
    framework: 'fastify' | 'express' | 'hono' | 'wordpress';
    database: 'postgresql' | 'mysql' | 'sqlite' | 'mongodb';
    orm?: 'prisma' | 'drizzle' | 'typeorm';
  };
  infrastructure?: {
    containerization: 'docker' | 'none';
    hosting: 'gcp' | 'aws' | 'vercel' | 'cloudflare' | 'self-hosted';
    ci?: 'github-actions' | 'gitlab-ci' | 'cloud-build';
  };
}

// File specification for code generation
export interface FileSpec {
  path: string;
  template: string;
  variables?: Record<string, unknown>;
}

// Dependency specification
export interface DependencySpec {
  name: string;
  version: string;
  dev?: boolean;
  workspace?: string;
}

// Code generation specifications
export interface CodeSpecs {
  scaffoldType: ScaffoldType;
  stackProfile: StackProfile;
  fileSpecs: FileSpec[];
  dependencies: DependencySpec[];
}

// Template variable for customization
export interface TemplateVariable {
  name: string;
  label: string;
  type: 'string' | 'number' | 'boolean' | 'select';
  default: unknown;
  options?: { label: string; value: unknown }[];
  description?: string;
  required?: boolean;
}

// Full workflow template definition
export interface WorkflowTemplateDefinition {
  id: string;
  name: string;
  description: string;
  category: TemplateCategory;
  complexity: TemplateComplexity;
  platform: TemplatePlatform;

  // Visual workflow
  nodes: WorkflowNode[];
  edges: WorkflowEdge[];

  // Code generation
  codeSpecs: CodeSpecs;

  // Customization
  variables: TemplateVariable[];

  // Metadata
  tags: string[];
  requiredAgents: string[];

  // Optional preview image
  previewImage?: string;
}

// Template metadata (lightweight version for listings)
export interface WorkflowTemplateMetadata {
  id: string;
  name: string;
  description: string;
  category: TemplateCategory;
  complexity: TemplateComplexity;
  platform: TemplatePlatform;
  tags: string[];
  nodeCount: number;
}

// Helper to extract metadata from full definition
export function toTemplateMetadata(template: WorkflowTemplateDefinition): WorkflowTemplateMetadata {
  return {
    id: template.id,
    name: template.name,
    description: template.description,
    category: template.category,
    complexity: template.complexity,
    platform: template.platform,
    tags: template.tags,
    nodeCount: template.nodes.length,
  };
}

// Code scaffold output
export interface CodeScaffold {
  directories: string[];
  files: { path: string; content: string }[];
  dependencies: { workspace: string; deps: DependencySpec[] }[];
  commands: { description: string; command: string }[];
}

// Workflow generation request (for AI agent)
export interface WorkflowGenerationRequest {
  prompt: string;
  category?: TemplateCategory;
  complexity?: TemplateComplexity;
  platform?: TemplatePlatform;
  variables?: Record<string, unknown>;
}

// Workflow generation response (from AI agent)
export interface WorkflowGenerationResponse {
  template: WorkflowTemplateDefinition;
  explanation: string;
  suggestedVariables?: TemplateVariable[];
}
