#!/bin/bash
# Development Environment Setup Script
# Generated by Terraform for ${environment} environment

set -euo pipefail

PROJECT_ID="${project_id}"
REGION="${region}"
ENVIRONMENT="${environment}"

echo "🚀 Setting up AgentWorks development environment..."
echo "Project: $PROJECT_ID"
echo "Region: $REGION"
echo "Environment: $ENVIRONMENT"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "$${BLUE}[INFO]$${NC} $1"
}

print_success() {
    echo -e "$${GREEN}[SUCCESS]$${NC} $1"
}

print_warning() {
    echo -e "$${YELLOW}[WARNING]$${NC} $1"
}

print_error() {
    echo -e "$${RED}[ERROR]$${NC} $1"
}

# Check prerequisites
check_prerequisites() {
    print_status "Checking prerequisites..."
    
    # Check if gcloud is installed
    if ! command -v gcloud &> /dev/null; then
        print_error "gcloud CLI is not installed. Please install it first."
        exit 1
    fi
    
    # Check if docker is installed
    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed. Please install it first."
        exit 1
    fi
    
    # Check if pnpm is installed
    if ! command -v pnpm &> /dev/null; then
        print_warning "pnpm is not installed. Installing..."
        npm install -g pnpm@9.14.2
    fi
    
    print_success "Prerequisites check completed"
}

# Configure gcloud
configure_gcloud() {
    print_status "Configuring gcloud..."
    
    # Set project
    gcloud config set project $PROJECT_ID
    gcloud config set compute/region $REGION
    gcloud config set run/region $REGION
    
    # Authenticate application default credentials
    print_status "Setting up Application Default Credentials..."
    gcloud auth application-default login
    
    # Configure Docker for Artifact Registry
    print_status "Configuring Docker for Artifact Registry..."
    gcloud auth configure-docker $REGION-docker.pkg.dev
    
    print_success "gcloud configuration completed"
}

# Install development tools
install_dev_tools() {
    print_status "Installing development tools..."
    
    # Install Cloud SQL Proxy
    if ! command -v cloud_sql_proxy &> /dev/null; then
        print_status "Installing Cloud SQL Proxy..."
        curl -o cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
        chmod +x cloud_sql_proxy
        sudo mv cloud_sql_proxy /usr/local/bin/
        print_success "Cloud SQL Proxy installed"
    fi
    
    # Install useful development tools
    if command -v apt-get &> /dev/null; then
        sudo apt-get update
        sudo apt-get install -y postgresql-client jq curl wget unzip
    elif command -v yum &> /dev/null; then
        sudo yum install -y postgresql jq curl wget unzip
    elif command -v brew &> /dev/null; then
        brew install postgresql jq curl wget
    fi
    
    print_success "Development tools installation completed"
}

# Setup local environment
setup_local_env() {
    print_status "Setting up local environment..."
    
    # Create .env.local if it doesn't exist
    if [ ! -f ".env.local" ]; then
        cat > .env.local << EOF
# Local development environment variables
# Generated by dev-setup script

NODE_ENV=development
PROJECT_ID=$PROJECT_ID
REGION=$REGION
ENVIRONMENT=$ENVIRONMENT

# Database (use Cloud SQL Proxy)
DATABASE_URL=postgresql://agentworks:password@localhost:5432/agentworks

# Service URLs (local development)
API_GATEWAY_URL=http://localhost:8080
CORE_SERVICE_URL=http://localhost:8000
AGENT_ORCHESTRATOR_URL=http://localhost:8001
PROVIDER_ROUTER_URL=http://localhost:8002
LOG_STREAMING_URL=http://localhost:8003
BILLING_SERVICE_URL=http://localhost:8004

# Pub/Sub topics (will be created by Terraform)
CARD_EVENTS_TOPIC=$PROJECT_ID-$ENVIRONMENT-card-events
AGENT_RUNS_TOPIC=$PROJECT_ID-$ENVIRONMENT-agent-runs
USAGE_EVENTS_TOPIC=$PROJECT_ID-$ENVIRONMENT-usage-events

# Storage buckets (will be created by Terraform)
LOGS_BUCKET=$PROJECT_ID-$ENVIRONMENT-logs
EXPORTS_BUCKET=$PROJECT_ID-$ENVIRONMENT-exports
UPLOADS_BUCKET=$PROJECT_ID-$ENVIRONMENT-uploads

# Add your API keys here:
# OPENAI_API_KEY=sk-...
# ANTHROPIC_API_KEY=sk-ant-...
# GOOGLE_AI_API_KEY=...
# NANOBANANA_API_KEY=...
# STRIPE_SECRET_KEY=sk_test_...
# STRIPE_PUBLISHABLE_KEY=pk_test_...
EOF
        print_success "Created .env.local file"
        print_warning "Please add your API keys to .env.local"
    else
        print_warning ".env.local already exists, skipping creation"
    fi
    
    # Install project dependencies
    print_status "Installing project dependencies..."
    pnpm install
    print_success "Dependencies installed"
    
    # Generate Prisma client
    print_status "Generating Prisma client..."
    pnpm --filter @agentworks/db generate
    print_success "Prisma client generated"
}

# Setup development database
setup_database() {
    print_status "Setting up development database connection..."
    
    # Start Cloud SQL Proxy in background
    print_status "Starting Cloud SQL Proxy..."
    
    # Get database connection name from Terraform output
    CONNECTION_NAME=$(gcloud sql instances describe agentworks-dev-postgres --format="value(connectionName)" 2>/dev/null || echo "")
    
    if [ -z "$CONNECTION_NAME" ]; then
        print_warning "Cloud SQL instance not found. Make sure Terraform infrastructure is deployed."
        print_status "You can start the proxy manually later with:"
        print_status "cloud_sql_proxy -instances=CONNECTION_NAME=tcp:5432"
    else
        print_status "Database connection name: $CONNECTION_NAME"
        
        # Check if proxy is already running
        if pgrep -f "cloud_sql_proxy" > /dev/null; then
            print_warning "Cloud SQL Proxy is already running"
        else
            print_status "Starting Cloud SQL Proxy..."
            nohup cloud_sql_proxy -instances=$CONNECTION_NAME=tcp:5432 > cloud_sql_proxy.log 2>&1 &
            sleep 3
            
            if pgrep -f "cloud_sql_proxy" > /dev/null; then
                print_success "Cloud SQL Proxy started successfully"
            else
                print_error "Failed to start Cloud SQL Proxy. Check cloud_sql_proxy.log for details."
            fi
        fi
    fi
}

# Create development scripts
create_dev_scripts() {
    print_status "Creating development scripts..."
    
    mkdir -p scripts
    
    # Start development servers script
    cat > scripts/start-dev.sh << 'EOF'
#!/bin/bash
# Start all development services
set -e

echo "🚀 Starting AgentWorks development servers..."

# Load environment variables
export $(grep -v '^#' .env.local | xargs)

# Start services in parallel using pnpm
pnpm run dev
EOF
    
    # Database management script
    cat > scripts/db-dev.sh << 'EOF'
#!/bin/bash
# Database management for development
set -e

command="$1"

case $command in
    "reset")
        echo "🔄 Resetting development database..."
        pnpm --filter @agentworks/db push --force-reset
        pnpm --filter @agentworks/db generate
        echo "✅ Database reset complete"
        ;;
    "migrate")
        echo "🔄 Running database migrations..."
        pnpm --filter @agentworks/db migrate
        echo "✅ Migrations complete"
        ;;
    "seed")
        echo "🌱 Seeding development data..."
        pnpm --filter @agentworks/db seed
        echo "✅ Seeding complete"
        ;;
    "studio")
        echo "🎨 Opening Prisma Studio..."
        pnpm --filter @agentworks/db studio
        ;;
    *)
        echo "Usage: $0 {reset|migrate|seed|studio}"
        exit 1
        ;;
esac
EOF
    
    # Make scripts executable
    chmod +x scripts/*.sh
    
    print_success "Development scripts created in scripts/ directory"
}

# Main setup function
main() {
    echo ""
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                AgentWorks Development Setup                  ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo ""
    
    check_prerequisites
    configure_gcloud
    install_dev_tools
    setup_local_env
    setup_database
    create_dev_scripts
    
    echo ""
    echo "╔══════════════════════════════════════════════════════════════╗"
    echo "║                     Setup Complete! 🎉                      ║"
    echo "╚══════════════════════════════════════════════════════════════╝"
    echo ""
    
    print_success "Development environment setup completed successfully!"
    echo ""
    print_status "Next steps:"
    echo "1. Add your API keys to .env.local"
    echo "2. Run database migrations: ./scripts/db-dev.sh migrate"
    echo "3. Seed development data: ./scripts/db-dev.sh seed"
    echo "4. Start development servers: ./scripts/start-dev.sh"
    echo ""
    print_status "Useful commands:"
    echo "- View database: ./scripts/db-dev.sh studio"
    echo "- Reset database: ./scripts/db-dev.sh reset"
    echo "- View logs: tail -f cloud_sql_proxy.log"
    echo "- Build project: pnpm build"
    echo "- Run tests: pnpm test"
    echo ""
}

# Run main function
main "$@"