steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/engagesuite-prod/agentworks/core-service:latest'
      - '-f'
      - 'apps/core-service/Dockerfile'
      - '--target'
      - 'production'
      - '.'
images:
  - 'us-central1-docker.pkg.dev/engagesuite-prod/agentworks/core-service:latest'
options:
  machineType: 'E2_HIGHCPU_8'
timeout: '1800s'
