#!/bin/bash

# AgentWorks - Lane 0: CEO CoPilot Q&A Session
# Orchestrates interactive Q&A session to build project Blueprint

set -e

PROJECT_ID=${1:-""}

if [ -z "$PROJECT_ID" ]; then
    echo "❌ Error: Project ID required"
    echo "Usage: $0 <project-id>"
    exit 1
fi

PROJECT_DIR="projects/$PROJECT_ID"
if [ ! -d "$PROJECT_DIR" ]; then
    echo "❌ Error: Project directory not found: $PROJECT_DIR"
    echo "Run: ./scripts/lane0/init-project.sh <project-name>"
    exit 1
fi

echo "🤖 Starting CEO CoPilot Q&A Session for Project: $PROJECT_ID"
echo "📁 Project Directory: $PROJECT_DIR"

# Load project configuration
PROJECT_CONFIG="$PROJECT_DIR/project.json"
PROJECT_NAME=$(jq -r '.name' "$PROJECT_CONFIG")

# Create session log
SESSION_ID=$(date +%s)
SESSION_LOG="$PROJECT_DIR/logs/agent_runs/copilot_session_$SESSION_ID.log"
mkdir -p "$(dirname "$SESSION_LOG")"

echo "💬 CEO CoPilot Session Log - $(date)" > "$SESSION_LOG"
echo "Project: $PROJECT_NAME ($PROJECT_ID)" >> "$SESSION_LOG"
echo "Session ID: $SESSION_ID" >> "$SESSION_LOG"
echo "----------------------------------------" >> "$SESSION_LOG"

# CEO CoPilot Q&A Template
cat << 'EOF'
🤖 CEO CoPilot Agent Activated

Welcome to AgentWorks Studio! I'm your strategic control tower. Let's start by 
understanding your project idea and building a comprehensive Blueprint.

I'll guide you through a structured Q&A session covering:
1. 🎯 Project Vision & Problem Statement
2. 👥 Target Users & Market
3. 🏗️ Core Value Proposition  
4. ⚙️ Technical & Business Constraints
5. 📊 Success Metrics & Risks

This session will generate your project Blueprint, which becomes the foundation
for all subsequent agent work. Let's begin!

═══════════════════════════════════════════════════════════════

EOF

# Q&A Session Template
cat << EOF > "$PROJECT_DIR/docs/QA_SESSION_$SESSION_ID.md"
# CEO CoPilot Q&A Session - $PROJECT_NAME

**Session ID:** $SESSION_ID  
**Date:** $(date +%Y-%m-%d)  
**Project:** $PROJECT_NAME ($PROJECT_ID)

---

## Section 1: Project Vision

### Q1: Problem Statement
**What problem are you solving? Who are your users? What's the core value proposition?**

*[Human Response]:*



### Q2: Market Context  
**What's your competitive landscape? How does this differ from existing solutions?**

*[Human Response]:*



---

## Section 2: Infrastructure Profile

### Q3: Technical Profile
**Based on your needs, here are three infrastructure options:**

**🌐 Standard SaaS**
- Web-only SaaS with auth, payments, and basic features
- *Choose This If:* Building a typical web application

**☁️ Next.js Cloud Run AlloyDB** 
- Full-stack SaaS with web and Expo mobile apps
- *Choose This If:* Need both web and mobile with advanced data

**🏢 Internal Tool**
- Internal business application with team management  
- *Choose This If:* Building for internal teams/workflows

**Which infrastructure profile fits your project?**

*[Human Response]:*



---

## Section 3: Core Requirements

### Q4: Feature Categories
**What are the main feature buckets? (e.g., User Management, Content Creation, Analytics, etc.)**

*[Human Response]:*



### Q5: Technical Constraints
**Any specific technology requirements, integrations, or constraints?**

*[Human Response]:*



---

## Section 4: Success & Risk

### Q6: Success Metrics
**How will you measure success? What are your key performance indicators?**

*[Human Response]:*



### Q7: Risk Assessment
**What are the main risks (technical, product, market, timeline)?**

*[Human Response]:*



---

## Section 5: Scope & Timeline

### Q8: MVP Scope
**What's the minimal viable product? What features are must-haves vs nice-to-haves?**

*[Human Response]:*



### Q9: Timeline & Resources
**What's your target timeline? Team size and technical expertise?**

*[Human Response]:*



---

## AI Agent Analysis

*This section will be populated by Strategy Agent based on responses above*

### Strategic Positioning
*[To be generated by Strategy Agent]*

### Feature Prioritization Matrix
*[To be generated by Strategy Agent]*

### Risk Mitigation Plan
*[To be generated by Strategy Agent]*

### Technical Architecture Recommendations
*[To be generated by Architect Agent]*

---

## Next Steps

After completing this Q&A:

1. ✅ **Strategy Agent** will analyze responses and update Blueprint
2. ✅ **Storyboard/UX Agent** will create user flows and wireframes  
3. ✅ **Human Review** and Blueprint approval
4. ➡️ **Move to Lane 1** for PRD and MVP definition

EOF

echo ""
echo "📝 Q&A Session template created: $PROJECT_DIR/docs/QA_SESSION_$SESSION_ID.md"
echo ""
echo "🎯 Instructions:"
echo "   1. Open the Q&A session file in your editor"
echo "   2. Complete all questions in the [Human Response] sections"
echo "   3. Save the file when done"
echo "   4. Run: ./scripts/lane0/strategy-analysis.sh $PROJECT_ID $SESSION_ID"
echo ""
echo "💡 Take your time - a thorough Q&A session leads to a better Blueprint!"
echo ""
echo "📂 Session File: $PROJECT_DIR/docs/QA_SESSION_$SESSION_ID.md"

# Update project with session info
jq --arg session_id "$SESSION_ID" --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)" \
  '.lanes["0"].cards += [{"type": "qa_session", "id": $session_id, "status": "in_progress", "created": $timestamp}] | 
   .agents.ceo_copilot.active = true |
   .agents.ceo_copilot.last_run = $timestamp' \
  "$PROJECT_CONFIG" > "$PROJECT_CONFIG.tmp" && mv "$PROJECT_CONFIG.tmp" "$PROJECT_CONFIG"

echo "🔄 Project status updated - CEO CoPilot session started"
echo "📊 Session ID: $SESSION_ID"