#!/bin/bash

# AgentWorks - Lane 0: UX Storyboard Agent
# Generates user flows and wireframes based on strategy analysis

set -e

PROJECT_ID=${1:-""}

if [ -z "$PROJECT_ID" ]; then
    echo "❌ Error: Project ID required"
    echo "Usage: $0 <project-id>"
    exit 1
fi

PROJECT_DIR="projects/$PROJECT_ID"
STRATEGY_FILE="$PROJECT_DIR/docs/STRATEGY_ANALYSIS.md"

if [ ! -f "$STRATEGY_FILE" ]; then
    echo "❌ Error: Strategy analysis not found: $STRATEGY_FILE"
    echo "Run: ./scripts/lane0/strategy-analysis.sh $PROJECT_ID <session-id>"
    exit 1
fi

echo "🎨 Starting UX Storyboard Agent for Project: $PROJECT_ID"
echo "📐 Generating user flows and wireframes..."

# Create UX analysis log
UX_LOG="$PROJECT_DIR/logs/agent_runs/ux_storyboards_$(date +%s).log"
echo "🎨 UX Storyboard Agent - $(date)" > "$UX_LOG"
echo "Project: $PROJECT_ID" >> "$UX_LOG"
echo "----------------------------------------" >> "$UX_LOG"

# Generate UX storyboards (would use LLM to analyze strategy + create flows)
cat > "$PROJECT_DIR/docs/UX_STORYBOARDS.md" << 'EOF'
# UX Storyboards & User Flows

**Generated by:** Storyboard/UX Agent  
**Based on:** Strategy Analysis & Blueprint  
**Date:** $(date +%Y-%m-%d)  

---

## User Journey Overview

*[UX Agent will analyze strategy and generate user-centered flows]*

### Primary User Personas
*[From Strategy Analysis - user segments]*

**Persona 1: [Primary User Type]**
- Demographics: *[Age, role, experience level]*
- Goals: *[What they want to accomplish]*
- Pain Points: *[Current frustrations]*
- Tech Comfort: *[Technical proficiency level]*

**Persona 2: [Secondary User Type]**
- Demographics: *[Profile details]*
- Goals: *[Objectives and needs]*
- Pain Points: *[Barriers to success]*
- Tech Comfort: *[Technical skills]*

---

## Core User Flows

### Flow 1: Onboarding & Setup
*[New user getting started]*

```
📱 LANDING PAGE
   ↓ [Sign Up / Get Started]
📝 REGISTRATION
   ↓ [Create Account]
🎯 WELCOME/ONBOARDING  
   ↓ [Complete Setup]
🏠 MAIN DASHBOARD
   ↓ [Begin First Action]
✅ FIRST VALUE DELIVERED
```

**Steps:**
1. **Landing Page**
   - Hero message: *[Value proposition]*
   - CTA: *[Primary action button]*
   - Social proof: *[Testimonials/logos]*

2. **Registration**
   - Email/password or OAuth
   - Basic profile setup
   - Terms acceptance

3. **Onboarding**
   - Welcome message
   - Feature tour (3-5 key features)
   - Setup wizard for core config

4. **Dashboard**
   - Empty state with clear next steps
   - Quick action buttons
   - Progress indicators

5. **First Value**
   - Complete core workflow
   - Achievement/success feedback
   - Next steps guidance

### Flow 2: Core Workflow
*[Main value delivery flow]*

```
🏠 DASHBOARD
   ↓ [Start Main Task]
📋 TASK SETUP
   ↓ [Configure Options]
⚡ PROCESSING/WORK
   ↓ [Review Results]
📊 RESULTS/OUTPUT
   ↓ [Save/Share/Export]
✅ COMPLETION
```

**Steps:**
1. **Dashboard Entry**
   - Quick access to main features
   - Recent items/history
   - Status indicators

2. **Task Initiation**
   - Input forms/wizards
   - Template selection
   - Configuration options

3. **Processing**
   - Progress indicators
   - Real-time updates
   - Cancel/modify options

4. **Results Review**
   - Output display
   - Edit/refine options
   - Quality checks

5. **Completion**
   - Save/export functionality
   - Sharing options
   - Next actions

### Flow 3: Advanced Features
*[Power user workflows]*

```
🏠 DASHBOARD
   ↓ [Advanced Tools]
🔧 ADVANCED INTERFACE
   ↓ [Complex Workflow]
📈 ANALYTICS/REPORTING
   ↓ [Export/Integration]
🔄 WORKFLOW AUTOMATION
```

---

## Screen Inventory

### 1. Authentication Screens
- **Landing Page**
  - Hero section with value prop
  - Feature highlights (3 key benefits)
  - Social proof section
  - Sign up/Login CTAs

- **Registration/Login**
  - Email/password fields
  - OAuth options (Google, GitHub)
  - Forgot password link
  - Terms and privacy links

### 2. Onboarding Screens
- **Welcome Screen**
  - Personalized greeting
  - Quick setup checklist
  - Skip option for returning users

- **Feature Tour** 
  - 3-5 key feature highlights
  - Interactive walkthrough
  - Skip/next navigation

- **Initial Setup**
  - Profile completion
  - Preferences configuration
  - Integration setup

### 3. Main Application Screens
- **Dashboard**
  - Navigation menu/sidebar
  - Quick action buttons
  - Recent activity feed
  - Status/progress widgets

- **Core Feature Screens**
  - *[Main workflow interfaces]*
  - Input forms and controls
  - Real-time feedback
  - Results/output views

- **Settings/Profile**
  - Account preferences
  - Billing/subscription
  - Integrations management
  - Support/help access

### 4. Mobile Considerations
*[If applicable based on infrastructure choice]*

- **Responsive Breakpoints**
  - Mobile: 320-768px
  - Tablet: 768-1024px  
  - Desktop: 1024px+

- **Mobile-First Features**
  - Touch-optimized controls
  - Swipe gestures
  - Offline capabilities
  - Push notifications

---

## Wireframes (Text-Based)

### Landing Page Layout
```
┌─────────────────────────────────────┐
│ LOGO    [Navigation Menu]    [Login]│
├─────────────────────────────────────┤
│                                     │
│         HERO HEADLINE               │
│      Compelling value prop          │
│                                     │
│     [Primary CTA Button]            │
│     [Secondary CTA]                 │
│                                     │
├─────────────────────────────────────┤
│  Feature 1   Feature 2   Feature 3  │
│  [Icon]      [Icon]      [Icon]     │
│  Brief desc  Brief desc  Brief desc │
├─────────────────────────────────────┤
│         Social Proof                │
│  "Customer testimonials and logos"  │
├─────────────────────────────────────┤
│ Footer Links    Contact    Legal    │
└─────────────────────────────────────┘
```

### Main Dashboard Layout
```
┌──────┬──────────────────────────────┐
│ LOGO │     [Search]    [Profile] ▼ │
├──────┼──────────────────────────────┤
│      │                              │
│ NAV  │        Main Content          │
│      │                              │
│ • Home│  ┌─────────┬─────────────┐   │
│ • Core│  │ Quick   │   Recent    │   │  
│ • Tools│ │ Actions │  Activity   │   │
│ • Settings│└────────┴─────────────┘   │
│      │                              │
│      │  [Primary Action Button]     │
│      │                              │
│      │  Status/Progress Widgets     │
└──────┴──────────────────────────────┘
```

### Core Feature Interface
```
┌─────────────────────────────────────┐
│  ← Back    Feature Name    Help ?   │
├─────────────────────────────────────┤
│                                     │
│  Input Section                      │
│  ┌─────────────────────────────────┐ │
│  │ Form fields, dropdowns, etc.   │ │
│  │                                │ │
│  └─────────────────────────────────┘ │
│                                     │
│  [Process/Submit Button]            │
│                                     │
│  Results/Output Section             │
│  ┌─────────────────────────────────┐ │
│  │ Generated content, data, etc.  │ │
│  │                                │ │
│  └─────────────────────────────────┘ │
│                                     │
│  [Save] [Export] [Share]            │
└─────────────────────────────────────┘
```

---

## Interaction Patterns

### Navigation Patterns
*[Based on infrastructure choice and complexity]*

**Primary Navigation:**
- Sidebar for complex apps
- Top nav for simple apps  
- Breadcrumbs for deep hierarchies

**Secondary Navigation:**
- Tabs for related sections
- Dropdown menus for options
- Context menus for actions

### Data Entry Patterns
*[Optimized for user efficiency]*

**Forms:**
- Progressive disclosure
- Smart defaults
- Inline validation
- Auto-save capabilities

**Bulk Operations:**
- Batch selection
- Bulk actions menu
- Progress indicators
- Undo/retry options

### Feedback Patterns
*[User communication strategy]*

**Success States:**
- Toast notifications
- Inline confirmations
- Progress celebrations
- Next step guidance

**Error States:**
- Clear error messages
- Recovery suggestions
- Help/support links
- Graceful degradation

---

## Accessibility Considerations

### WCAG Compliance
- **Perceivable:** Alt text, color contrast, text scaling
- **Operable:** Keyboard navigation, focus management
- **Understandable:** Clear language, consistent patterns
- **Robust:** Semantic HTML, screen reader support

### Inclusive Design
- Multi-language support (if applicable)
- Various technical skill levels
- Different device capabilities
- Diverse user contexts

---

## Next Steps

1. **Human Review:** Validate user flows match expectations
2. **Design Mockups:** Create visual designs (future phase)
3. **PRD Agent:** Translate flows into detailed requirements
4. **Prototype:** Build clickable prototype (if needed)
5. **User Testing:** Validate flows with real users

---

## Validation Checklist

- [ ] **User flows align with strategy goals**
- [ ] **Onboarding delivers first value quickly**
- [ ] **Core workflow is efficient and clear**
- [ ] **Error states and edge cases covered**
- [ ] **Mobile experience optimized**
- [ ] **Accessibility requirements addressed**
- [ ] **Technical feasibility confirmed**

---

*These storyboards were generated by AgentWorks UX Agent based on Strategy Analysis*
EOF

echo "🎨 UX storyboards generated" | tee -a "$UX_LOG"

# Update Blueprint with UX completion
BLUEPRINT_FILE="$PROJECT_DIR/docs/BLUEPRINT.md"
sed -i 's/- \[ \] \*\*UX Storyboards:\*\* Pending/- [x] **UX Storyboards:** Complete ✅/' "$BLUEPRINT_FILE"

# Update project status
PROJECT_CONFIG="$PROJECT_DIR/project.json"
jq --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)" \
  '.agents.storyboard_ux.active = true |
   .agents.storyboard_ux.last_run = $timestamp |
   .lanes["0"].cards += [{"type": "ux_storyboards", "status": "completed", "created": $timestamp}]' \
  "$PROJECT_CONFIG" > "$PROJECT_CONFIG.tmp" && mv "$PROJECT_CONFIG.tmp" "$PROJECT_CONFIG"

echo "" | tee -a "$UX_LOG"  
echo "✅ UX storyboards completed!" | tee -a "$UX_LOG"
echo "📄 Storyboards created: $PROJECT_DIR/docs/UX_STORYBOARDS.md" | tee -a "$UX_LOG"
echo "📋 Blueprint updated with UX completion status" | tee -a "$UX_LOG"
echo "" | tee -a "$UX_LOG"
echo "🔄 Next step: Finalize Blueprint for approval"
echo "   Run: ./scripts/lane0/finalize-blueprint.sh $PROJECT_ID"
echo ""
echo "📊 Lane 0 Progress:"
echo "   ✅ CEO CoPilot Q&A Complete"
echo "   ✅ Strategy Analysis Complete" 
echo "   ✅ UX Storyboards Complete"
echo "   ⏳ Human Review & Approval Pending"