import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import { useSearchParams } from 'react-router-dom';
import {
  FileText,
  Target,
  Users,
  Clock,
  Bot,
  Sparkles,
  Loader2,
  CheckCheck,
  Save,
  Link2,
  RefreshCw,
  Download,
  FolderOpen,
  AlertCircle,
  Check,
} from 'lucide-react';
import { useWorkspaceStore } from '../../stores/workspace';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { api } from '../../lib/api';
import { useCoPilot } from '../../contexts/CoPilotContext';
import DocConflictModal from './DocConflictModal';

const DOCUMENT_TABS = [
  { id: 'blueprint', label: 'Blueprint', content: 'blueprint', icon: FileText },
  { id: 'prd', label: 'PRD', content: 'prd', icon: FileText },
  { id: 'mvp', label: 'MVP', content: 'mvp', icon: Target },
  { id: 'playbook', label: 'Agent Playbook', content: 'playbook', icon: Users },
];

const EMPTY_PLACEHOLDER = '';

type SaveStatus = 'idle' | 'saving' | 'saved' | 'error';

export default function PlanningWorkspace() {
  const { currentProjectId } = useWorkspaceStore();
  const { openDrawer } = useCoPilot();
  const queryClient = useQueryClient();
  const [searchParams, setSearchParams] = useSearchParams();
  const [activeDocument, setActiveDocument] = useState('blueprint');
  const [editorMode, setEditorMode] = useState<'edit' | 'preview'>('edit');
  const [documentContent, setDocumentContent] = useState(EMPTY_PLACEHOLDER);
  const [saveStatus, setSaveStatus] = useState<SaveStatus>('idle');
  const saveTimeoutRef = useRef<NodeJS.Timeout | null>(null);
  const lastSavedContentRef = useRef<string>('');

  // Sync activeDocument with URL search params (bidirectional)
  useEffect(() => {
    const docParam = searchParams.get('doc');
    if (docParam && DOCUMENT_TABS.some(tab => tab.id === docParam)) {
      if (docParam !== activeDocument) {
        setActiveDocument(docParam);
      }
    }
  }, [searchParams, activeDocument]);

  const { data: components = [] } = useQuery({
    queryKey: ['project-components', currentProjectId],
    queryFn: () => currentProjectId ? api.projects.listComponents(currentProjectId) : [],
    enabled: !!currentProjectId,
  });

  // Fetch project documents (from ProjectDoc table - generated by CoPilot)
  const { data: projectDocsData } = useQuery({
    queryKey: ['project-docs', currentProjectId],
    queryFn: () => currentProjectId ? api.projects.getDocs(currentProjectId) : { docs: [] },
    enabled: !!currentProjectId,
  });

  // Fetch document sync info (file paths, sync status)
  const { data: docsInfoData, refetch: refetchDocsInfo } = useQuery({
    queryKey: ['docs-info', currentProjectId],
    queryFn: () => currentProjectId ? api.projects.getDocsInfo(currentProjectId) : null,
    enabled: !!currentProjectId,
  });

  // Sync document to filesystem mutation
  const syncDocMutation = useMutation({
    mutationFn: async (type: string) => {
      if (!currentProjectId) throw new Error('No project selected');
      return api.projects.syncDoc(currentProjectId, type);
    },
    onSuccess: () => {
      refetchDocsInfo();
      queryClient.invalidateQueries({ queryKey: ['project-docs', currentProjectId] });
    },
  });

  // Import document from filesystem mutation
  const importDocMutation = useMutation({
    mutationFn: async (type: string) => {
      if (!currentProjectId) throw new Error('No project selected');
      return api.projects.importDoc(currentProjectId, type);
    },
    onSuccess: () => {
      refetchDocsInfo();
      queryClient.invalidateQueries({ queryKey: ['project-docs', currentProjectId] });
    },
  });

  // Conflict modal state
  const [conflictModal, setConflictModal] = useState<{
    isOpen: boolean;
    docType: string;
    dbContent: string;
    fileContent: string;
    dbUpdatedAt: string;
    fileMtime: string;
  } | null>(null);

  // Track which docs have been auto-synced this session (to prevent loops)
  const autoSyncedRef = useRef<Set<string>>(new Set());

  // Auto-sync mutation - handles timestamp-based sync
  const autoSyncMutation = useMutation({
    mutationFn: async (type: string) => {
      if (!currentProjectId) throw new Error('No project selected');
      return api.projects.autoSyncDoc(currentProjectId, type);
    },
    onSuccess: (result, type) => {
      if (result.action === 'conflict') {
        // Show conflict modal
        setConflictModal({
          isOpen: true,
          docType: type,
          dbContent: result.dbContent || '',
          fileContent: result.fileContent || '',
          dbUpdatedAt: result.dbUpdatedAt || '',
          fileMtime: result.fileMtime || '',
        });
      } else if (result.action === 'imported' || result.action === 'synced' || result.action === 'created') {
        // Refresh data after successful auto-sync
        refetchDocsInfo();
        queryClient.invalidateQueries({ queryKey: ['project-docs', currentProjectId] });
      }
    },
  });

  // Resolve conflict mutation
  const resolveConflictMutation = useMutation({
    mutationFn: async ({ type, resolution }: { type: string; resolution: 'keep_db' | 'keep_file' }) => {
      if (!currentProjectId) throw new Error('No project selected');
      return api.projects.resolveDocConflict(currentProjectId, type, resolution);
    },
    onSuccess: () => {
      setConflictModal(null);
      refetchDocsInfo();
      queryClient.invalidateQueries({ queryKey: ['project-docs', currentProjectId] });
    },
  });

  // Auto-sync on page load - check for file_newer or conflict states
  useEffect(() => {
    if (!currentProjectId || !docsInfoData?.documents) return;

    // Find documents that need auto-sync (file_newer, db_newer, or conflict)
    const docsNeedingSync = docsInfoData.documents.filter(doc => {
      // Skip if already synced this session
      if (autoSyncedRef.current.has(doc.type)) return false;
      // Only auto-sync for specific states
      return doc.syncState === 'file_newer' || doc.syncState === 'conflict';
    });

    // Auto-sync each document
    docsNeedingSync.forEach(doc => {
      autoSyncedRef.current.add(doc.type);
      autoSyncMutation.mutate(doc.type);
    });
  }, [currentProjectId, docsInfoData?.documents]);

  // Get current document's file info
  const currentDocInfo = useMemo(() => {
    if (!docsInfoData?.documents) return null;
    return docsInfoData.documents.find(d => d.type === activeDocument);
  }, [docsInfoData, activeDocument]);

  const { data: projectData } = useQuery({
    queryKey: ['project', currentProjectId],
    queryFn: () => currentProjectId ? api.projects.get(currentProjectId) : null,
    enabled: !!currentProjectId,
  });

  // Merge components with project docs (ProjectDoc takes priority for document types)
  const mergedComponents = useMemo(() => {
    const docTypes = ['blueprint', 'prd', 'mvp', 'playbook'];
    const result = [...components];

    // Add or override with ProjectDoc data
    projectDocsData?.docs?.forEach((doc: any) => {
      const docType = doc.type.toLowerCase();
      if (docTypes.includes(docType)) {
        // Find existing component index
        const existingIndex = result.findIndex((c: any) =>
          c.type === docType || c.name === docType
        );

        // Create a component-compatible format from ProjectDoc
        const docComponent = {
          id: doc.id,
          type: docType,
          name: docType,
          data: { content: doc.content },
          createdAt: doc.createdAt,
          updatedAt: doc.updatedAt,
        };

        if (existingIndex >= 0) {
          // Replace existing component with ProjectDoc data
          result[existingIndex] = docComponent;
        } else {
          // Add new component from ProjectDoc
          result.push(docComponent);
        }
      }
    });

    return result;
  }, [components, projectDocsData?.docs]);

  // Auto-save mutation for documents - saves to ProjectDoc table AND syncs to filesystem
  const saveMutation = useMutation({
    mutationFn: async ({ type, content }: { type: string; content: string }) => {
      if (!currentProjectId) throw new Error('No project selected');
      // Use updateDoc to save to ProjectDoc table (also syncs to filesystem automatically)
      return api.projects.updateDoc(currentProjectId, type, content);
    },
    onSuccess: () => {
      setSaveStatus('saved');
      lastSavedContentRef.current = documentContent;
      // Invalidate both project-docs and docs-info queries
      queryClient.invalidateQueries({ queryKey: ['project-docs', currentProjectId] });
      queryClient.invalidateQueries({ queryKey: ['docs-info', currentProjectId] });
      setTimeout(() => setSaveStatus('idle'), 2000);
    },
    onError: () => {
      setSaveStatus('error');
      setTimeout(() => setSaveStatus('idle'), 3000);
    },
  });

  // Debounced auto-save for documents
  const debouncedSave = useCallback((content: string) => {
    if (saveTimeoutRef.current) {
      clearTimeout(saveTimeoutRef.current);
    }

    // Only save if content has actually changed
    if (content === lastSavedContentRef.current) return;

    saveTimeoutRef.current = setTimeout(() => {
      if (content.trim() && currentProjectId) {
        setSaveStatus('saving');
        saveMutation.mutate({ type: activeDocument, content });
      }
    }, 1500); // 1.5 second debounce
  }, [activeDocument, currentProjectId, saveMutation]);

  useEffect(() => {
    const doc = mergedComponents.find((c: any) => c.type === activeDocument || c.name === activeDocument);
    if (doc?.data?.content) {
      setDocumentContent(doc.data.content);
      lastSavedContentRef.current = doc.data.content;
    } else {
      setDocumentContent(EMPTY_PLACEHOLDER);
      lastSavedContentRef.current = '';
    }
    setSaveStatus('idle');
  }, [activeDocument, mergedComponents]);

  // Handle content change with auto-save
  const handleContentChange = useCallback((e: React.ChangeEvent<HTMLTextAreaElement>) => {
    const newContent = e.target.value;
    setDocumentContent(newContent);
    debouncedSave(newContent);
  }, [debouncedSave]);

  // Manual save function for explicit save button
  const handleManualSave = useCallback(() => {
    // Clear any pending auto-save
    if (saveTimeoutRef.current) {
      clearTimeout(saveTimeoutRef.current);
    }

    // Only save if there's content and it has changed
    if (documentContent.trim() && currentProjectId && documentContent !== lastSavedContentRef.current) {
      setSaveStatus('saving');
      saveMutation.mutate({ type: activeDocument, content: documentContent });
    }
  }, [activeDocument, currentProjectId, documentContent, saveMutation]);

  const currentPhase = projectData?.phase || 'welcome';
  const isInDiscovery = ['welcome', 'vision', 'requirements', 'goals', 'roles', 'architecture'].includes(currentPhase);
  const hasContent = documentContent.trim().length > 0;

  const handleDocumentTabClick = (docId: string) => {
    setActiveDocument(docId);
    setSearchParams({ doc: docId }, { replace: true });
  };

  const getSaveStatusIndicator = (status: SaveStatus = saveStatus) => {
    switch (status) {
      case 'saving':
        return (
          <div className="flex items-center gap-1 px-3 py-1 bg-blue-100 text-blue-700 rounded-full">
            <Loader2 className="h-3 w-3 animate-spin" />
            <span className="text-xs font-medium">Saving...</span>
          </div>
        );
      case 'saved':
        return (
          <div className="flex items-center gap-1 px-3 py-1 bg-green-100 text-green-700 rounded-full">
            <CheckCheck className="h-3 w-3" />
            <span className="text-xs font-medium">Saved</span>
          </div>
        );
      case 'error':
        return (
          <div className="flex items-center gap-1 px-3 py-1 bg-red-100 text-red-700 rounded-full">
            <span className="text-xs font-medium">Save failed</span>
          </div>
        );
      default:
        return (
          <div className="flex items-center gap-1 px-3 py-1 bg-orange-100 text-orange-700 rounded-full">
            <Clock className="h-3 w-3" />
            <span className="text-xs font-medium">Draft</span>
          </div>
        );
    }
  };

  return (
    <div className="h-full flex bg-white relative">
      {/* Main Content - Document Editor (full width, sidebar moved to LeftPanel) */}
      <div className="flex-1 flex flex-col">
        {/* Document Header */}
        <div className="flex items-center justify-between p-4 border-b border-slate-200 bg-white">
          <div className="flex items-center gap-4">
            <h1 className="text-lg font-semibold text-slate-900">Project Documentation</h1>
            {getSaveStatusIndicator()}
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={handleManualSave}
              disabled={saveStatus === 'saving' || saveStatus === 'saved' || !hasContent}
              className={`flex items-center gap-2 px-4 py-1.5 text-sm font-medium rounded-lg transition-colors ${
                saveStatus === 'saving'
                  ? 'bg-blue-100 text-blue-600 cursor-wait'
                  : saveStatus === 'saved'
                  ? 'bg-green-100 text-green-600 cursor-default'
                  : !hasContent
                  ? 'bg-slate-100 text-slate-400 cursor-not-allowed'
                  : 'bg-blue-600 text-white hover:bg-blue-700'
              }`}
            >
              {saveStatus === 'saving' ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : saveStatus === 'saved' ? (
                <CheckCheck className="h-4 w-4" />
              ) : (
                <Save className="h-4 w-4" />
              )}
              {saveStatus === 'saving' ? 'Saving...' : saveStatus === 'saved' ? 'Saved' : 'Save'}
            </button>
            <div className="flex items-center bg-slate-100 rounded-lg p-0.5">
              <button
                onClick={() => setEditorMode('edit')}
                className={`px-3 py-1.5 text-sm font-medium rounded-md transition-colors ${
                  editorMode === 'edit'
                    ? 'bg-white text-slate-900 shadow-sm'
                    : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                Edit
              </button>
              <button
                onClick={() => setEditorMode('preview')}
                className={`px-3 py-1.5 text-sm font-medium rounded-md transition-colors ${
                  editorMode === 'preview'
                    ? 'bg-white text-slate-900 shadow-sm'
                    : 'text-slate-600 hover:text-slate-900'
                }`}
              >
                Preview
              </button>
            </div>
          </div>
        </div>

        {/* Document Tabs */}
        <div className="border-b border-slate-200 bg-white">
          <div className="flex items-center gap-1 px-4">
            {DOCUMENT_TABS.map((tab) => {
              const TabIcon = tab.icon;
              const tabDocInfo = docsInfoData?.documents?.find(d => d.type === tab.id);
              return (
                <button
                  key={tab.id}
                  onClick={() => handleDocumentTabClick(tab.id)}
                  className={`flex items-center gap-2 px-4 py-3 text-sm font-medium border-b-2 transition-colors ${
                    activeDocument === tab.id
                      ? 'border-blue-600 text-blue-600'
                      : 'border-transparent text-slate-600 hover:text-slate-900 hover:border-slate-300'
                  }`}
                >
                  <TabIcon className="h-4 w-4" />
                  {tab.label}
                  {/* Sync state indicator dots */}
                  {tabDocInfo?.syncState === 'in_sync' && tabDocInfo.hasFileContent && (
                    <span className="w-2 h-2 rounded-full bg-green-500" title="In sync with file" />
                  )}
                  {tabDocInfo?.syncState === 'file_newer' && (
                    <span className="w-2 h-2 rounded-full bg-blue-500" title="File is newer" />
                  )}
                  {tabDocInfo?.syncState === 'db_newer' && (
                    <span className="w-2 h-2 rounded-full bg-purple-500" title="DB is newer" />
                  )}
                  {tabDocInfo?.syncState === 'conflict' && (
                    <span className="w-2 h-2 rounded-full bg-orange-500 animate-pulse" title="Conflict - both modified" />
                  )}
                </button>
              );
            })}
          </div>
        </div>

        {/* File Path Indicator - shows link to /docs and sync status */}
        {currentDocInfo && docsInfoData?.localPath && (
          <div className="px-4 py-2 bg-slate-50 border-b border-slate-200 flex items-center justify-between">
            <div className="flex items-center gap-2 text-xs text-slate-600">
              <FolderOpen className="h-3.5 w-3.5" />
              <span className="font-mono">{currentDocInfo.filePath || `${docsInfoData.docsDir}/${currentDocInfo.fileName}`}</span>

              {/* Sync State Badge */}
              {currentDocInfo.syncState === 'in_sync' && (
                <span className="flex items-center gap-1 px-2 py-0.5 bg-green-100 text-green-700 rounded-full">
                  <Check className="h-3 w-3" />
                  <span>Synced</span>
                </span>
              )}
              {currentDocInfo.syncState === 'file_newer' && (
                <span className="flex items-center gap-1 px-2 py-0.5 bg-blue-100 text-blue-700 rounded-full">
                  <Download className="h-3 w-3" />
                  <span>File newer</span>
                </span>
              )}
              {currentDocInfo.syncState === 'db_newer' && (
                <span className="flex items-center gap-1 px-2 py-0.5 bg-purple-100 text-purple-700 rounded-full">
                  <RefreshCw className="h-3 w-3" />
                  <span>DB newer</span>
                </span>
              )}
              {currentDocInfo.syncState === 'conflict' && (
                <span className="flex items-center gap-1 px-2 py-0.5 bg-orange-100 text-orange-700 rounded-full">
                  <AlertCircle className="h-3 w-3" />
                  <span>Conflict</span>
                </span>
              )}
              {currentDocInfo.syncState === 'file_missing' && (
                <span className="flex items-center gap-1 px-2 py-0.5 bg-slate-100 text-slate-600 rounded-full">
                  <Link2 className="h-3 w-3" />
                  <span>File not created</span>
                </span>
              )}
            </div>
            <div className="flex items-center gap-2">
              {/* Resolve Conflict button */}
              {currentDocInfo.syncState === 'conflict' && (
                <button
                  onClick={() => autoSyncMutation.mutate(activeDocument)}
                  disabled={autoSyncMutation.isPending}
                  className="flex items-center gap-1 px-2 py-1 text-xs font-medium text-orange-600 hover:bg-orange-50 rounded transition-colors disabled:opacity-50"
                  title="Resolve sync conflict"
                >
                  {autoSyncMutation.isPending ? (
                    <Loader2 className="h-3 w-3 animate-spin" />
                  ) : (
                    <AlertCircle className="h-3 w-3" />
                  )}
                  Resolve Conflict
                </button>
              )}
              {/* Sync to File button */}
              <button
                onClick={() => syncDocMutation.mutate(activeDocument)}
                disabled={syncDocMutation.isPending}
                className="flex items-center gap-1 px-2 py-1 text-xs font-medium text-blue-600 hover:bg-blue-50 rounded transition-colors disabled:opacity-50"
                title="Save database content to file"
              >
                {syncDocMutation.isPending ? (
                  <Loader2 className="h-3 w-3 animate-spin" />
                ) : (
                  <RefreshCw className="h-3 w-3" />
                )}
                Sync to File
              </button>
              {/* Import from File button (only show if file exists) */}
              {currentDocInfo.hasFileContent && (
                <button
                  onClick={() => importDocMutation.mutate(activeDocument)}
                  disabled={importDocMutation.isPending}
                  className="flex items-center gap-1 px-2 py-1 text-xs font-medium text-slate-600 hover:bg-slate-100 rounded transition-colors disabled:opacity-50"
                  title="Import content from file to database"
                >
                  {importDocMutation.isPending ? (
                    <Loader2 className="h-3 w-3 animate-spin" />
                  ) : (
                    <Download className="h-3 w-3" />
                  )}
                  Import from File
                </button>
              )}
            </div>
          </div>
        )}

        {/* Document Content */}
        <div className="flex-1 flex overflow-hidden">
          {!hasContent ? (
            <div className="flex-1 flex items-center justify-center bg-slate-50">
              <div className="text-center max-w-md">
                <div className="w-16 h-16 mx-auto mb-4 rounded-full bg-gradient-to-br from-blue-100 to-indigo-100 flex items-center justify-center">
                  <Sparkles className="h-8 w-8 text-blue-600" />
                </div>
                <h3 className="text-lg font-semibold text-slate-900 mb-2">No {activeDocument.charAt(0).toUpperCase() + activeDocument.slice(1)} Yet</h3>
                <p className="text-sm text-slate-600 mb-6">
                  {isInDiscovery 
                    ? "Complete the CoPilot discovery flow to generate your project documents."
                    : "This document hasn't been created yet. Use CoPilot to generate it."}
                </p>
                <button
                  onClick={openDrawer}
                  className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
                >
                  <Bot className="h-4 w-4" />
                  Open CoPilot
                </button>
              </div>
            </div>
          ) : editorMode === 'edit' ? (
            <div className="flex-1 flex">
              <div className="flex-1 p-6">
                <textarea
                  value={documentContent}
                  onChange={handleContentChange}
                  className="w-full h-full font-mono text-sm leading-relaxed border-none outline-none resize-none bg-transparent"
                  placeholder="Start writing your project documentation..."
                />
              </div>
              
              <div className="flex-1 p-6 bg-slate-50 border-l border-slate-200 overflow-auto">
                <div className="prose prose-sm max-w-none">
                  {documentContent.split('\n').map((line, index) => {
                    if (line.startsWith('# ')) {
                      return <h1 key={index} className="text-2xl font-bold text-slate-900 mb-4">{line.substring(2)}</h1>;
                    } else if (line.startsWith('## ')) {
                      return <h2 key={index} className="text-lg font-semibold text-slate-900 mb-3 mt-6">{line.substring(3)}</h2>;
                    } else if (line.startsWith('### ')) {
                      return <h3 key={index} className="text-base font-semibold text-slate-900 mb-2 mt-4">{line.substring(4)}</h3>;
                    } else if (line.startsWith('- ')) {
                      return <li key={index} className="text-slate-700 mb-1">{line.substring(2)}</li>;
                    } else if (line.startsWith('*') && line.endsWith('*')) {
                      return <p key={index} className="text-xs text-slate-500 italic mt-4 border-t border-slate-200 pt-4">{line.substring(1, line.length - 1)}</p>;
                    } else if (line.trim() === '') {
                      return <br key={index} />;
                    } else {
                      return <p key={index} className="text-slate-700 mb-3 leading-relaxed">{line}</p>;
                    }
                  })}
                </div>
              </div>
            </div>
          ) : (
            <div className="flex-1 p-6 overflow-auto">
              <div className="prose prose-slate max-w-none">
                <div className="space-y-6">
                  {documentContent.split('\n').map((line, index) => {
                    if (line.startsWith('# ')) {
                      return <h1 key={index} className="text-3xl font-bold text-slate-900">{line.substring(2)}</h1>;
                    } else if (line.startsWith('## ')) {
                      return <h2 key={index} className="text-xl font-semibold text-slate-900 mt-8">{line.substring(3)}</h2>;
                    } else if (line.startsWith('### ')) {
                      return <h3 key={index} className="text-lg font-semibold text-slate-900 mt-6">{line.substring(4)}</h3>;
                    } else if (line.startsWith('- ')) {
                      return <li key={index} className="text-slate-700">{line.substring(2)}</li>;
                    } else if (line.startsWith('*') && line.endsWith('*')) {
                      return <p key={index} className="text-sm text-slate-500 italic mt-8 border-t border-slate-200 pt-6">{line.substring(1, line.length - 1)}</p>;
                    } else if (line.trim() === '') {
                      return <div key={index} className="h-4" />;
                    } else {
                      return <p key={index} className="text-slate-700 leading-relaxed">{line}</p>;
                    }
                  })}
                </div>
              </div>
            </div>
          )}
        </div>
      </div>

      {/* Conflict Resolution Modal */}
      {conflictModal && (
        <DocConflictModal
          isOpen={conflictModal.isOpen}
          onClose={() => setConflictModal(null)}
          docType={conflictModal.docType}
          dbContent={conflictModal.dbContent}
          fileContent={conflictModal.fileContent}
          dbUpdatedAt={conflictModal.dbUpdatedAt}
          fileMtime={conflictModal.fileMtime}
          onResolve={(resolution) => {
            resolveConflictMutation.mutate({
              type: conflictModal.docType,
              resolution,
            });
          }}
          isResolving={resolveConflictMutation.isPending}
        />
      )}
    </div>
  );
}