#!/bin/bash

# AgentWorks - Lane 1: MVP Agent - Define Minimal Viable Product
# Analyzes PRD and defines MVP scope with feature prioritization

set -e

PROJECT_ID=${1:-""}

if [ -z "$PROJECT_ID" ]; then
    echo "❌ Error: Project ID required"
    echo "Usage: $0 <project-id>"
    exit 1
fi

PROJECT_DIR="projects/$PROJECT_ID"
PROJECT_CONFIG="$PROJECT_DIR/project.json"
PRD_FILE="$PROJECT_DIR/docs/PRD.md"

if [ ! -f "$PRD_FILE" ]; then
    echo "❌ Error: PRD not found: $PRD_FILE"
    echo "Generate PRD first: ./scripts/lane1/generate-prd.sh $PROJECT_ID"
    exit 1
fi

PROJECT_NAME=$(jq -r '.name' "$PROJECT_CONFIG")
echo "🎯 Defining MVP for Project: $PROJECT_NAME ($PROJECT_ID)"

# Create MVP analysis log
MVP_LOG="$PROJECT_DIR/logs/agent_runs/mvp_definition_$(date +%s).log"
echo "🎯 MVP Agent - $(date)" > "$MVP_LOG"
echo "Project: $PROJECT_NAME ($PROJECT_ID)" >> "$MVP_LOG"
echo "----------------------------------------" >> "$MVP_LOG"

# Generate MVP definition (would use LLM to analyze PRD and prioritize features)
cat > "$PROJECT_DIR/docs/MVP.md" << EOF
# $PROJECT_NAME - MVP Definition

**Version:** 1.0  
**Date:** $(date +%Y-%m-%d)  
**Owner:** $(jq -r '.blueprint_approval.approved_by // "Unknown"' "$PROJECT_CONFIG")  
**Generated by:** MVP Agent (OpenAI GPT-4)  
**Based on:** PRD v1.0  

---

## 1. MVP Goal

*[MVP Agent analyzes PRD and defines focused MVP scope]*

### MVP Objective
*[Clear, measurable objective for the MVP release]*

### Success Criteria
- **User Acquisition:** *[Target number of users/signups]*
- **User Engagement:** *[Key engagement metrics]*
- **Value Delivery:** *[How quickly users reach first value]*
- **Validation:** *[What we need to prove with MVP]*

### Timeline Target
**MVP Timeline:** *[Estimated development time based on feature scope]*  
**Launch Target:** *[Target launch date]*

---

## 2. MVP Scope

### 2.1 Core Value Proposition
*[The single most important value this MVP delivers]*

**Primary User Need:** *[The #1 problem being solved]*  
**Core Solution:** *[How MVP addresses this need]*  
**Success Metric:** *[How we measure MVP success]*

### 2.2 Target User for MVP
*[Focused user segment for initial release]*

**Primary MVP User:** *[Most important user type for MVP]*
- **Why This User First:** *[Strategic reasoning]*
- **MVP User Journey:** *[Simplified user flow for MVP]*
- **Success Definition:** *[How this user defines success]*

---

## 3. MVP Features

### 3.1 MUST HAVE (Core MVP)
*[Absolutely essential features for MVP to be viable]*

#### Feature 1: *[Core Feature Name]*
- **Description:** *[What it does and why it's critical]*
- **User Story:** As a *[user]*, I want *[action]* so that *[benefit]*
- **MVP Scope:** *[Simplified version for MVP]*
- **Success Metric:** *[How we measure this feature's success]*
- **Estimated Effort:** *[Development time estimate]*

#### Feature 2: *[Essential Feature Name]*
*[Similar structure for each must-have feature]*

#### Feature 3: *[Required Feature Name]*
*[Continue for all absolutely necessary features]*

### 3.2 SHOULD HAVE (MVP Enhancement)
*[Important features that enhance MVP but aren't critical]*

#### Feature A: *[Enhancement Feature]*
- **Description:** *[What it adds to user experience]*
- **Why Important:** *[Value it provides]*
- **MVP Inclusion:** *[Include if time permits]*
- **Post-MVP Priority:** *[High/Medium/Low for v1.1]*

### 3.3 COULD HAVE (Future Versions)
*[Nice-to-have features postponed to post-MVP]*

#### Feature X: *[Future Feature]*
- **Description:** *[What it would do]*
- **Why Postponed:** *[Reason for exclusion from MVP]*
- **Future Priority:** *[v1.1, v1.2, v2.0, etc.]*

### 3.4 WON'T HAVE (Explicitly Excluded)
*[Features explicitly excluded to maintain focus]*

#### Excluded Feature Y: *[Excluded Feature]*
- **Description:** *[What we're not building]*
- **Why Excluded:** *[Strategic reason for exclusion]*
- **Revisit Timeline:** *[When we might reconsider]*

---

## 4. MVP User Experience

### 4.1 Simplified User Flow
*[Streamlined version of UX storyboards for MVP]*

```
🚀 LANDING → 📝 SIGNUP → 🎯 ONBOARDING → 🏠 DASHBOARD → ⚡ CORE ACTION → ✅ SUCCESS
```

**MVP User Journey:**
1. **Discovery:** *[How users find the MVP]*
2. **Signup:** *[Simplified registration process]*
3. **Onboarding:** *[Minimal setup to reach value]*
4. **First Value:** *[Core action that delivers value]*
5. **Retention:** *[What brings users back]*

### 4.2 MVP Interface Priorities

**Essential UI Elements:**
- *[Critical interface components for MVP]*
- *[Must-have navigation elements]*
- *[Core interaction patterns]*

**Simplified for MVP:**
- *[Complex features reduced to basics]*
- *[Advanced options postponed]*
- *[Streamlined workflows]*

**MVP Design Principles:**
- **Simplicity:** Minimize cognitive load
- **Speed to Value:** Get users to success quickly
- **Core Focus:** Excel at the primary use case
- **Iteration Ready:** Easy to enhance post-launch

---

## 5. Technical MVP Scope

### 5.1 Architecture for MVP
*[Simplified technical implementation]*

**MVP Tech Stack:**
- **Frontend:** *[Minimal frontend setup]*
- **Backend:** *[Core API endpoints only]*
- **Database:** *[Essential data models]*
- **Infrastructure:** *[Basic deployment setup]*

**Technical Debt Acceptance:**
- *[What shortcuts we'll take for MVP speed]*
- *[What we'll refactor post-MVP]*
- *[Technical limitations accepted for MVP]*

### 5.2 MVP Integrations

**Essential Integrations:**
- *[Third-party services required for MVP]*
- *[Payment processing if needed for MVP]*
- *[Analytics for measuring MVP success]*

**Postponed Integrations:**
- *[Complex integrations saved for post-MVP]*
- *[Nice-to-have third-party services]*

---

## 6. MVP Success Metrics

### 6.1 Product Metrics
*[How we'll measure MVP success]*

**Activation Metrics:**
- User signup rate
- Onboarding completion rate  
- Time to first value
- Feature adoption rates

**Engagement Metrics:**
- Daily/Monthly active users
- Session duration and frequency
- Core feature usage
- User retention rates

**Value Delivery Metrics:**
- *[Product-specific success indicators]*
- *[User satisfaction scores]*
- *[Net Promoter Score (NPS)]*

### 6.2 Business Metrics
*[Business success indicators for MVP]*

**Growth Metrics:**
- User acquisition rate
- Conversion rates (if applicable)
- Referral rates
- Market penetration

**Validation Metrics:**
- Product-market fit indicators
- Customer feedback quality
- Support ticket volume and types
- Feature request patterns

---

## 7. MVP Development Plan

### 7.1 Development Phases

#### Phase 1: Foundation (Weeks 1-2)
- **Infrastructure Setup**
  - Development environment
  - CI/CD pipeline
  - Basic deployment
- **Core Backend**
  - Authentication system
  - Essential API endpoints
  - Database setup

#### Phase 2: Core Features (Weeks 3-4)
- **Primary Feature Implementation**
  - *[Most critical user-facing feature]*
- **Basic Frontend**
  - Landing and signup pages
  - Core user interface
  - Basic navigation

#### Phase 3: Integration & Polish (Weeks 5-6)  
- **Feature Integration**
  - End-to-end workflows
  - User onboarding
  - Error handling
- **Quality Assurance**
  - Testing and bug fixes
  - Performance optimization
  - Security review

### 7.2 Acceptance Criteria for MVP
*[What must be true for MVP launch]*

**Functional Requirements:**
- [ ] All MUST HAVE features implemented and tested
- [ ] User can complete core workflow end-to-end
- [ ] Authentication and security working properly
- [ ] Basic error handling and validation in place

**Quality Requirements:**
- [ ] No critical bugs in core workflows
- [ ] Performance meets minimum acceptable levels
- [ ] Basic accessibility requirements met
- [ ] Mobile responsiveness for core features

**Business Requirements:**  
- [ ] Analytics tracking implemented
- [ ] User feedback collection in place
- [ ] Basic customer support process established
- [ ] Legal/compliance requirements met

---

## 8. Post-MVP Roadmap

### 8.1 Version 1.1 (MVP + 4 weeks)
*[First enhancement based on MVP feedback]*

**Priority Additions:**
- *[SHOULD HAVE features from MVP analysis]*
- *[User feedback-driven improvements]*
- *[Performance and UX enhancements]*

### 8.2 Version 1.2 (MVP + 8 weeks)
*[Second iteration with expanded functionality]*

**Feature Expansions:**
- *[COULD HAVE features that show promise]*
- *[Advanced user workflows]*
- *[Integration enhancements]*

### 8.3 Version 2.0 (MVP + 12 weeks)
*[Major feature release]*

**Significant Additions:**
- *[Complex features requiring significant development]*
- *[New user segments or use cases]*
- *[Platform or architecture improvements]*

---

## 9. Risk Assessment & Mitigation

### 9.1 MVP-Specific Risks

**Development Risks:**
- **Risk:** Feature scope creep during development
- **Mitigation:** Strict feature freeze and change control
- **Monitoring:** Weekly scope review meetings

**Market Risks:**
- **Risk:** MVP doesn't resonate with target users
- **Mitigation:** Early user testing and feedback collection
- **Monitoring:** User engagement metrics and feedback

**Technical Risks:**
- **Risk:** Performance issues with simplified architecture
- **Mitigation:** Performance testing and optimization plan
- **Monitoring:** Response time and user experience metrics

### 9.2 Success Factors for MVP

**Critical Success Factors:**
1. **Focus:** Resist feature additions that don't serve core value
2. **Speed:** Launch quickly to start learning from real users  
3. **Quality:** Ensure core functionality works reliably
4. **Feedback:** Collect and act on user feedback rapidly
5. **Iteration:** Be ready to pivot based on learnings

---

## 10. Launch Plan

### 10.1 MVP Launch Strategy

**Soft Launch Phase (Week 1):**
- Limited user invites (friends, family, beta testers)
- Monitor core metrics and collect feedback
- Fix critical issues and polish rough edges

**Public Launch Phase (Week 2-4):**
- Broader user acquisition campaign
- Press and marketing activities
- Scale infrastructure as needed

### 10.2 Success Validation

**Week 1 Targets:** *[Immediate post-launch metrics]*
**Week 4 Targets:** *[Month 1 success criteria]*
**Week 12 Targets:** *[Quarter 1 validation metrics]*

---

## Appendices

### Appendix A: Feature Comparison Matrix

| Feature | Full PRD | MVP | v1.1 | v1.2 | v2.0 | Rationale |
|---------|----------|-----|------|------|------|-----------|
| *[Feature 1]* | Complex | Simple | Enhanced | Full | - | *[Why this evolution]* |
| *[Feature 2]* | Full | Full | - | - | - | *[Core to MVP]* |
| *[Feature 3]* | Full | - | Simple | Enhanced | Full | *[Post-MVP priority]* |

### Appendix B: User Feedback Collection Plan

**Feedback Channels:**
- In-app feedback widget
- User interview schedule  
- Analytics and behavior tracking
- Support ticket analysis

**Key Questions for MVP Users:**
- Did you accomplish what you came here to do?
- How easy was it to get started?
- What would you change about the experience?
- How likely are you to recommend this to others?

---

**Document Status:** Ready for Review and Feature Card Creation  
**Next Step:** Create feature cards with ./scripts/lane1/create-feature-cards.sh  
**Generated by:** AgentWorks MVP Agent based on PRD v1.0
EOF

echo "🎯 MVP definition generated successfully" | tee -a "$MVP_LOG"

# Update project status
jq --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)" \
  '.agents.mvp.last_run = $timestamp |
   .lanes["1"].cards += [{"type": "mvp_definition", "status": "completed", "created": $timestamp, "artifact": "docs/MVP.md"}]' \
  "$PROJECT_CONFIG" > "$PROJECT_CONFIG.tmp" && mv "$PROJECT_CONFIG.tmp" "$PROJECT_CONFIG"

echo "" | tee -a "$MVP_LOG"
echo "✅ MVP Definition Complete!" | tee -a "$MVP_LOG"
echo "🎯 MVP scope: $PROJECT_DIR/docs/MVP.md" | tee -a "$MVP_LOG"
echo "" | tee -a "$MVP_LOG"
echo "📋 Next Steps:"
echo "   1. Review MVP scope: cat $PROJECT_DIR/docs/MVP.md"
echo "   2. Create feature cards: ./scripts/lane1/create-feature-cards.sh $PROJECT_ID"
echo "   3. Proceed to architecture: ./scripts/build/design-architecture.sh $PROJECT_ID"
echo ""
echo "🤖 MVP Agent Status: Complete"  
echo "📊 MVP Features Prioritized: MUST/SHOULD/COULD/WON'T HAVE"
echo "➡️ Ready for Feature Card Generation"