#!/bin/bash

# AgentWorks - Lane 1: PRD Agent - Generate Product Requirements Document
# Creates comprehensive PRD from approved Blueprint

set -e

PROJECT_ID=${1:-""}

if [ -z "$PROJECT_ID" ]; then
    echo "❌ Error: Project ID required"
    echo "Usage: $0 <project-id>"
    exit 1
fi

PROJECT_DIR="projects/$PROJECT_ID"
PROJECT_CONFIG="$PROJECT_DIR/project.json"
BLUEPRINT_FILE="$PROJECT_DIR/docs/BLUEPRINT.md"
STRATEGY_FILE="$PROJECT_DIR/docs/STRATEGY_ANALYSIS.md"
UX_FILE="$PROJECT_DIR/docs/UX_STORYBOARDS.md"

# Verify prerequisites
if [ ! -f "$BLUEPRINT_FILE" ]; then
    echo "❌ Error: Blueprint not found: $BLUEPRINT_FILE"
    exit 1
fi

if [ "$(jq -r '.blueprint_approved // false' "$PROJECT_CONFIG")" != "true" ]; then
    echo "❌ Error: Blueprint not approved yet"
    echo "Run: ./scripts/lane1/approve-blueprint.sh $PROJECT_ID"
    exit 1
fi

PROJECT_NAME=$(jq -r '.name' "$PROJECT_CONFIG")
echo "📄 Generating PRD for Project: $PROJECT_NAME ($PROJECT_ID)"

# Create PRD generation log
PRD_LOG="$PROJECT_DIR/logs/agent_runs/prd_generation_$(date +%s).log"
echo "📄 PRD Agent - $(date)" > "$PRD_LOG"
echo "Project: $PROJECT_NAME ($PROJECT_ID)" >> "$PRD_LOG"
echo "----------------------------------------" >> "$PRD_LOG"

# Generate comprehensive PRD (would use LLM to analyze Blueprint + Strategy + UX)
cat > "$PROJECT_DIR/docs/PRD.md" << EOF
# $PROJECT_NAME - Product Requirements Document (PRD)

**Version:** 1.0  
**Date:** $(date +%Y-%m-%d)  
**Owner:** $(jq -r '.blueprint_approval.approved_by // "Unknown"' "$PROJECT_CONFIG")  
**Generated by:** PRD Agent (OpenAI GPT-4)  
**Based on:** Approved Blueprint v1.0  

---

## 1. Executive Summary

*[PRD Agent will analyze approved Blueprint and generate comprehensive requirements]*

### Project Vision
*[From approved Blueprint - problem, users, solution]*

### Success Criteria
*[Measurable objectives from Blueprint approval]*

### Scope Overview
*[High-level feature categories from strategy analysis]*

---

## 2. Product Overview

### 2.1 Product Description
*[Detailed description based on Blueprint vision and strategy]*

**Core Purpose:**
*[What problem does this solve and for whom?]*

**Primary Value Proposition:**  
*[Key benefits users receive]*

**Competitive Advantage:**
*[What makes this different/better than alternatives]*

### 2.2 Target Users

#### Primary Persona: *[From Strategy Analysis]*
- **Demographics:** *[Age, role, industry, etc.]*
- **Needs:** *[Core problems and pain points]*
- **Goals:** *[What they want to accomplish]*
- **Behaviors:** *[How they currently solve problems]*
- **Tech Comfort:** *[Technical proficiency level]*

#### Secondary Persona: *[If applicable]*
- **Demographics:** *[Profile information]*  
- **Needs:** *[Different or overlapping needs]*
- **Goals:** *[Their specific objectives]*

### 2.3 Market Context
*[From Strategy Analysis - competitive landscape]*

**Market Size:** *[Addressable market assessment]*
**Competitive Landscape:** *[Key competitors and differentiation]*
**Market Trends:** *[Relevant industry trends and opportunities]*

---

## 3. Functional Requirements

### 3.1 Core Features

#### Feature 1: *[Primary Feature from Strategy]*
**Description:** *[What this feature does and why it's important]*

**User Stories:**
- As a *[user type]*, I want to *[action]* so that *[benefit]*
- As a *[user type]*, I want to *[action]* so that *[benefit]*
- As a *[user type]*, I want to *[action]* so that *[benefit]*

**Acceptance Criteria:**
- [ ] *[Specific testable requirement]*
- [ ] *[Specific testable requirement]*
- [ ] *[Specific testable requirement]*

**Business Rules:**
- *[Any business logic or constraints]*

**Dependencies:**
- *[Other features or systems this depends on]*

#### Feature 2: *[Secondary Feature]*
*[Similar structure as Feature 1]*

#### Feature 3: *[Additional Features]*
*[Continue for all major features from strategy analysis]*

### 3.2 User Authentication & Management
*[Based on UX storyboards and infrastructure choice]*

**Registration/Login:**
- Email/password authentication
- OAuth integration (Google, GitHub, etc.)
- Password reset functionality
- Email verification

**User Profiles:**
- Basic profile information
- Preferences and settings
- Usage tracking and analytics opt-in/out

**User Roles:** *[If applicable]*
- *[Define different user types and permissions]*

### 3.3 User Interface Requirements
*[Based on UX storyboards]*

**Navigation:**
- *[Primary navigation structure]*
- *[Secondary navigation patterns]*
- *[Mobile navigation approach]*

**Core Workflows:**
- *[Key user flows from UX storyboards]*
- *[Step-by-step process descriptions]*

**Responsive Design:**
- Mobile-first approach
- Tablet optimization
- Desktop experience
- *[Specific breakpoints and behaviors]*

---

## 4. Non-Functional Requirements

### 4.1 Performance Requirements
*[Based on infrastructure choice and expected usage]*

**Response Time:**
- Page load time: < 2 seconds
- API response time: < 500ms
- Search results: < 1 second

**Throughput:**
- Concurrent users: *[Expected capacity]*
- Transactions per second: *[Peak load handling]*
- Data processing: *[Batch job requirements]*

**Scalability:**
- Auto-scaling capabilities
- Database performance at scale
- CDN for static assets

### 4.2 Security Requirements

**Authentication & Authorization:**
- Secure password policies
- Session management
- Role-based access control
- API authentication (OAuth 2.0, JWT)

**Data Protection:**
- Encryption in transit (HTTPS/TLS)
- Encryption at rest
- PII data handling
- GDPR compliance (if applicable)

**Infrastructure Security:**
- DDoS protection
- SQL injection prevention
- XSS protection
- CSRF protection

### 4.3 Availability & Reliability

**Uptime:** 99.9% availability target
**Backup:** Daily automated backups with point-in-time recovery
**Monitoring:** Real-time application and infrastructure monitoring
**Disaster Recovery:** Recovery time objective (RTO) and recovery point objective (RPO)

### 4.4 Compatibility

**Browser Support:**
- Chrome (last 2 versions)
- Firefox (last 2 versions)
- Safari (last 2 versions)
- Edge (last 2 versions)

**Mobile Support:**
- iOS Safari (last 2 versions)
- Android Chrome (last 2 versions)
- Progressive Web App capabilities

**API Compatibility:**
- RESTful API design
- JSON request/response format
- API versioning strategy

---

## 5. Technical Requirements

### 5.1 Architecture Overview
*[Based on infrastructure choice from Blueprint]*

**Infrastructure Profile:** *[Standard SaaS / Next.js Cloud Run / Internal Tool]*

**Technology Stack:**
- **Frontend:** *[React/Vue, based on infrastructure choice]*
- **Backend:** *[Node.js/Python, based on infrastructure choice]*
- **Database:** *[PostgreSQL/MySQL, based on requirements]*
- **Cloud Platform:** *[GCP/AWS, based on Blueprint decision]*
- **CI/CD:** *[GitHub Actions/GitLab CI]*

### 5.2 Integration Requirements
*[From Blueprint constraints and technical requirements]*

**Third-Party Services:**
- *[Required integrations from Blueprint]*
- *[Payment processing, if applicable]*
- *[Analytics and tracking]*
- *[External APIs]*

**Data Sources:**
- *[External data requirements]*
- *[Import/export capabilities]*
- *[Data synchronization needs]*

### 5.3 Development Requirements

**Code Quality:**
- TypeScript for type safety
- ESLint for code linting
- Prettier for code formatting
- Unit test coverage > 80%

**Documentation:**
- API documentation (OpenAPI/Swagger)
- Component documentation (Storybook)
- Development setup guide
- Deployment documentation

---

## 6. User Experience Requirements

### 6.1 Usability Requirements
*[From UX storyboards]*

**Ease of Use:**
- Intuitive navigation
- Clear call-to-action buttons
- Consistent design patterns
- Help and documentation

**Onboarding:**
- *[User onboarding flow from UX storyboards]*
- Progressive disclosure of features
- Guided tutorials for complex features
- Empty states with clear next steps

### 6.2 Accessibility Requirements

**WCAG Compliance:** Level AA compliance
**Keyboard Navigation:** Full keyboard accessibility
**Screen Reader Support:** Semantic HTML and ARIA labels
**Color Contrast:** 4.5:1 minimum contrast ratio
**Text Scaling:** Support for 200% zoom

### 6.3 Internationalization
*[If applicable based on target market]*

**Language Support:** *[Languages to support]*
**Localization:** Date/time formats, number formats, currency
**RTL Support:** *[If supporting right-to-left languages]*

---

## 7. Data Requirements

### 7.1 Data Models
*[Key entities and relationships]*

**User Data:**
- User profiles and authentication
- User preferences and settings
- Usage analytics and behavior

**Core Business Data:**
- *[Primary data entities from feature requirements]*
- *[Relationships between entities]*
- *[Data validation rules]*

### 7.2 Data Storage

**Database Design:**
- Relational database for transactional data
- Caching layer for performance
- File storage for uploads/assets

**Data Retention:**
- User data retention policy
- Analytics data retention
- Backup and archival strategy

**Privacy & Compliance:**
- Data anonymization capabilities
- User data export/deletion (GDPR)
- Audit logging for sensitive operations

---

## 8. Success Metrics & Analytics

### 8.1 Key Performance Indicators
*[From Blueprint success metrics]*

**Product KPIs:**
- *[User engagement metrics]*
- *[Feature adoption rates]*
- *[User retention rates]*

**Business KPIs:**
- *[Revenue metrics, if applicable]*
- *[Conversion rates]*
- *[Customer acquisition cost]*

**Technical KPIs:**
- System uptime and performance
- API response times
- Error rates and resolution times

### 8.2 Analytics Implementation

**Tracking Requirements:**
- User behavior analytics
- Feature usage tracking
- Performance monitoring
- Error tracking and alerting

**Privacy Considerations:**
- User consent for tracking
- Data anonymization
- Opt-out capabilities

---

## 9. Launch Requirements

### 9.1 Minimum Viable Product (MVP)
*[To be defined by MVP Agent in next step]*

**MVP Scope:** *[Will be defined in MVP.md]*
**Success Criteria:** *[MVP-specific success metrics]*
**Timeline:** *[MVP development timeline]*

### 9.2 Go-to-Market Strategy
*[From strategy analysis]*

**Launch Plan:**
- *[Soft launch vs. public launch strategy]*
- *[User acquisition channels]*
- *[Marketing and communication plan]*

**Support Requirements:**
- User documentation and help center
- Customer support channels
- Bug reporting and feedback collection

---

## 10. Risks & Assumptions

### 10.1 Technical Risks
*[From Blueprint risk analysis]*

**High Priority Risks:**
- *[Major technical risks and mitigation strategies]*

**Medium Priority Risks:**
- *[Secondary risks and monitoring plans]*

### 10.2 Product Risks

**Market Risks:**
- *[Competitive threats and market changes]*
- *[User adoption challenges]*

**Execution Risks:**
- *[Development timeline risks]*
- *[Resource availability risks]*

### 10.3 Assumptions

**User Behavior Assumptions:**
- *[Key assumptions about how users will interact with the product]*

**Technical Assumptions:**
- *[Assumptions about technology choices and capabilities]*

**Business Assumptions:**
- *[Market and business model assumptions]*

---

## 11. Appendices

### Appendix A: Glossary
*[Definitions of key terms and concepts]*

### Appendix B: Reference Documents
- BLUEPRINT.md (v1.0, approved $(date +%Y-%m-%d))
- STRATEGY_ANALYSIS.md
- UX_STORYBOARDS.md
- Technical Architecture (to be created)

### Appendix C: Change Log
- v1.0 ($(date +%Y-%m-%d)): Initial PRD generated from approved Blueprint

---

**Document Status:** Draft - Requires review and approval  
**Next Step:** Define MVP scope with MVP Agent  
**Generated by:** AgentWorks PRD Agent based on approved Blueprint v1.0
EOF

echo "📄 PRD generated successfully" | tee -a "$PRD_LOG"

# Update project status
jq --arg timestamp "$(date -u +%Y-%m-%dT%H:%M:%S.%3NZ)" \
  '.agents.prd.last_run = $timestamp |
   .lanes["1"].cards += [{"type": "prd_generation", "status": "completed", "created": $timestamp, "artifact": "docs/PRD.md"}]' \
  "$PROJECT_CONFIG" > "$PROJECT_CONFIG.tmp" && mv "$PROJECT_CONFIG.tmp" "$PROJECT_CONFIG"

echo "" | tee -a "$PRD_LOG"
echo "✅ PRD Generation Complete!" | tee -a "$PRD_LOG"
echo "📄 PRD created: $PROJECT_DIR/docs/PRD.md" | tee -a "$PRD_LOG"
echo "" | tee -a "$PRD_LOG"
echo "📋 Next Steps:"
echo "   1. Review PRD: cat $PROJECT_DIR/docs/PRD.md"
echo "   2. Define MVP: ./scripts/lane1/define-mvp.sh $PROJECT_ID"
echo "   3. Create feature cards: ./scripts/lane1/create-feature-cards.sh $PROJECT_ID"
echo ""
echo "🤖 PRD Agent Status: Complete"
echo "➡️ Ready for MVP Agent activation"